# Generated by Django 3.2.25 on 2024-06-05 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leki_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSubstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_sub_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AddedSubstances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('main_active_substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leki_app.activesubstance')),
                ('other_substances', models.ManyToManyField(related_name='other_substances', to='leki_app.ActiveSubstance')),
            ],
        ),
        migrations.DeleteModel(
            name='Lek',
        ),
        migrations.DeleteModel(
            name='Lekarz',
        ),
        migrations.DeleteModel(
            name='Skutki',
        ),
        migrations.DeleteModel(
            name='Substancja',
        ),
    ]
