# Generated by Django 3.2.25 on 2024-06-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leki_app', '0002_auto_20240605_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddedSubstances',
            new_name='AddedSubstance',
        ),
    ]
