# Generated by Django 3.2.25 on 2024-06-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leki_app', '0003_rename_addedsubstances_addedsubstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='other_substances',
        ),
    ]
