# Generated by Django 3.2.25 on 2024-06-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leki_app', '0004_remove_drug_other_substances'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='other_substances',
            field=models.ManyToManyField(blank=True, to='leki_app.AddedSubstance'),
        ),
    ]
