# Generated by Django 5.0.6 on 2024-06-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leki_app', '0006_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies_for_active',
            field=models.ManyToManyField(blank=True, to='leki_app.activesubstance'),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies_for_added',
            field=models.ManyToManyField(blank=True, to='leki_app.addedsubstance'),
        ),
    ]
