# Generated by Django 5.0.6 on 2024-06-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leki_app', '0007_patient_allergies_for_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
    ]
