# Generated by Django 5.0.6 on 2024-06-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leki_app', '0008_alter_patient_treatment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
