# Generated by Django 5.0.6 on 2024-06-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leki_app', '0009_patient_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='drugs',
        ),
        migrations.AddField(
            model_name='patient',
            name='drug_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
