# Generated by Django 5.0.6 on 2024-06-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leki_app', '0010_remove_patient_drugs_patient_drug_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_drugs',
            field=models.ManyToManyField(blank=True, to='leki_app.drug'),
        ),
    ]
