# Generated by Django 5.0.6 on 2024-06-20 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leki_app', '0011_patient_current_drugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='current_drugs',
        ),
        migrations.AddField(
            model_name='patient',
            name='current_drugs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leki_app.drug'),
        ),
    ]
